/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "LCD.h"
#include "DHT11.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

uint8_t temperature, humidity;

int main(void)
{
    HAL_Init();
    SystemClock_Config();
    MX_GPIO_Init();
    MX_TIM1_Init();
    HAL_TIM_Base_Start(&htim1);

    LCD_Init();

    while (1)
    {
        if(DHT11_Read(&temperature, &humidity))
        {
            LCD_Clear();

            char msg1[16], msg2[16];
            sprintf(msg1, "TEMP: %d C", temperature);
            sprintf(msg2, "HUM : %d %%", humidity);

            LCD_SetCursor(0,0);
            LCD_Send_String(msg1);

            LCD_SetCursor(1,0);
            LCD_Send_String(msg2);
        }
        else
        {
            LCD_Clear();
            LCD_Send_String("DHT11 Error!");
        }

        HAL_Delay(1000);
    }
}
